FROM node:18-alpine

RUN ["mkdir", "/install"]

ADD ["./package.json", "/install"]
WORKDIR /install
ENV NODE_PATH=/install/node_modules
RUN npm install 

WORKDIR /client

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]