version: '3.9'

services:
  reverseproxy:
    build:
        context: ./reverseproxy
        dockerfile: nginx.Dockerfile
    container_name: reverseproxy
    ports:
        - "443:443"
        - "80:80"
    restart: always
    depends_on:
        - api
        - frontend
    networks:
        - public
  api:
    build:
      target: dev
  redis:
    ports:
      - 6379:6379
  frontend:
    build:
      target: dev
