import { IWeekplan } from './weekplan.interface';

export const defaultWeekplan: IWeekplan = {
    id: 1,
    userId: 'hans',
    startDate: new Date('2023-06-05'),
    endDate: new Date('2023-07-05'),
    weekplanEntry: [
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
        {
            id: 1,
            date: new Date('2023-07-05'),
            weekplanId: 2,
            recipeId: 5,
            recipe: {
                id: 1,
                name: 'Yummy recipe',
                img: 'http://url',
                description: 'Very good recipe',
                cookingTime: 12,
                preparingTime: 15,
                totalTime: 16,
                servings: 2,
                tags: ['hahah', 'hohoh'],
                formOfDiet: 'vegan',
            },
        },
    ],
};
