###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine
ENV DATABASE_URL $DATABASE_URL
WORKDIR /app

COPY . /app
ENV NODE_ENV development

COPY --chown=node:node package*.json .
RUN npm ci && npm cache clean --force && npm prune

COPY --chown=node:node . .
RUN npm run build

#RUN npm ci

CMD [ "npx", "prisma", "migrate", "dev" ]
EXPOSE 3000
